#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CANSniffer.Resource", IsApplication=true)]

namespace CANSniffer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int connectionTextView = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int deviceNameTextView = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int filter1EditText = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int filter2EditText = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int filter3EditText = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int filter4EditText = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int filter5EditText = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int filter6EditText = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout2 = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout3 = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout4 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout5 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int mask1EditText = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int mask2EditText = 2131099658;
			
			// aapt resource value: 0x7f060015
			public const int myButton = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int pingListView = 2131099668;
			
			// aapt resource value: 0x7f060005
			public const int prefsButton = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int resetMaskFilterButton = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int startstopButton = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int textView1 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int textView2 = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Settings = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int nodevice = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int start = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int stop = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int hexkeyboard = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
